name: Greetings

on:
  pull_request:
    types:
      - opened
  issues:
    types:
      - opened

permissions:
  contents: read

jobs:
  greeting:
    name: Greet First-Time Contributors
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    if: |
      github.event_name == 'issues' ||
      (
        github.event.pull_request.user.login != 'dependabot[bot]' &&
        github.event.pull_request.user.login != 'renovate[bot]'
      )
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - uses: actions/first-interaction@1c4688942c71f71d4f5502a26ea67c331730fa4d # v3.1.0
        with:
          issue_message:
            "Hello and thank you for opening an issue. We'll look into it as
            soon as possible."
          pr_message:
            "Hello and thank you for opening a pull request. We'll review it and
            make a decision as soon as possible."
